# Generated by Django 4.2.2 on 2023-06-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField()),
                ('rpm', models.FloatField()),
                ('fuel_level', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
